* add restart service command;

diff --git a/config/commutator b/config/commutator
--- a/config/commutator
+++ b/config/commutator
@@ -126,6 +126,24 @@ case "$1" in
 	do_reload
 	log_end_msg $?
 	;;
+ restart)
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	    0|1)
+		do_start
+		case "$?" in
+		    0) log_end_msg 0 ;;
+		    1) log_end_msg 1 ;; # Old process is still running
+		    *) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	    *)
+		# Failed to stop
+		log_end_msg 1
+	    ;;
+	esac
+	;;
   *)
 	echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
 	exit 3
